import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "min-h-screen bg-background antialiased"
        )}
      >
        <div className="relative flex min-h-screen flex-col bg-background">
          <div className="border-border/40">
            <div className="flex flex-col min-h-screen mx-auto w-full border-border/40 min-[1800px]:max-w-[1536px] min-[1800px]:border-x">
              <main className="flex-1 items-center justify-center h-full">
                {children}
              </main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
